@startuml Qix
main -> Qix : .getCoordYP()
Qix -> main : return coordYP
main -> Qix : .getCoordXP()
Qix -> main : return coordXP
main -> Player : .getCoordYP()
Player -> main : return coordYP
main -> Player : .getCoordXP()
Player -> main : return coordXP
main -> Spark : .getCoordYP()
Spark -> main : return coordYP
main -> Spark : .getCoordXP()
Spark -> main : return coordXP
main -> Graph : .setupGrid()
Graph -> Graph : .updateWalls()
main -> Player : .move()
Player -> Graph : .getGrid()
Graph -> Player : return grid
Player -> Character : .move()
Player -> Graph : .getCGrid()
Graph -> Player : return cGrid
Player -> Graph : .updateGridLine()
Player -> Player : .hitSelf()
Player -> Graph : .updateGridBox()
Graph -> Graph: .updateWalls()
Graph -> Graph : .checkWin()
main -> Spark : .move()
Spark -> Character : .move()
main -> Spark : .getCoordYP()
Spark -> main : return coordYP
main -> Spark : .getCoordXP()
Spark -> main : return coordXP
main -> Player : .checkLostLife()
main -> Player : .getLife()
Player -> main : return lifeForce()
main -> Qix : .move()
Qix -> Character : .move()
Qix -> Player : .qixHit()
main -> Player : .getLife()
Player -> main : return lifeForce()
@enduml
